/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as ZohoSuccessIndexRouteImport } from './routes/zoho-success/index'
import { Route as ZohoFailedIndexRouteImport } from './routes/zoho-failed/index'
import { Route as AuthRoutecopyRouteImport } from './routes/_auth/route copy'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/_auth/forgot-password/index'
import { Route as AppZohoIndexRouteImport } from './routes/_app/zoho/index'
import { Route as AppWorkshopIndexRouteImport } from './routes/_app/workshop/index'
import { Route as AppVideosIndexRouteImport } from './routes/_app/videos/index'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AppSubCoursesIndexRouteImport } from './routes/_app/sub-courses/index'
import { Route as AppRoutinesIndexRouteImport } from './routes/_app/routines/index'
import { Route as AppPaymentsIndexRouteImport } from './routes/_app/payments/index'
import { Route as AppMockTestsIndexRouteImport } from './routes/_app/mock-tests/index'
import { Route as AppMockTestBookingsIndexRouteImport } from './routes/_app/mock-test-bookings/index'
import { Route as AppHolidaysIndexRouteImport } from './routes/_app/holidays/index'
import { Route as AppExamsIndexRouteImport } from './routes/_app/exams/index'
import { Route as AppExamBookingsIndexRouteImport } from './routes/_app/exam-bookings/index'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppEnglishTestIndexRouteImport } from './routes/_app/english-test/index'
import { Route as AppDemoIndexRouteImport } from './routes/_app/demo/index'
import { Route as AppCoursesIndexRouteImport } from './routes/_app/courses/index'
import { Route as AppCoursePackagesIndexRouteImport } from './routes/_app/course-packages/index'
import { Route as AppCourseBookingsIndexRouteImport } from './routes/_app/course-bookings/index'
import { Route as AppContactsIndexRouteImport } from './routes/_app/contacts/index'
import { Route as AppConsultationsIndexRouteImport } from './routes/_app/consultations/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/_dashboard/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ZohoSuccessIndexRoute = ZohoSuccessIndexRouteImport.update({
  id: '/zoho-success/',
  path: '/zoho-success/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZohoFailedIndexRoute = ZohoFailedIndexRouteImport.update({
  id: '/zoho-failed/',
  path: '/zoho-failed/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoutecopyRoute = AuthRoutecopyRouteImport.update({
  id: '/route copy',
  path: '/route copy',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppZohoIndexRoute = AppZohoIndexRouteImport.update({
  id: '/zoho/',
  path: '/zoho/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkshopIndexRoute = AppWorkshopIndexRouteImport.update({
  id: '/workshop/',
  path: '/workshop/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVideosIndexRoute = AppVideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSubCoursesIndexRoute = AppSubCoursesIndexRouteImport.update({
  id: '/sub-courses/',
  path: '/sub-courses/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRoutinesIndexRoute = AppRoutinesIndexRouteImport.update({
  id: '/routines/',
  path: '/routines/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPaymentsIndexRoute = AppPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMockTestsIndexRoute = AppMockTestsIndexRouteImport.update({
  id: '/mock-tests/',
  path: '/mock-tests/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMockTestBookingsIndexRoute =
  AppMockTestBookingsIndexRouteImport.update({
    id: '/mock-test-bookings/',
    path: '/mock-test-bookings/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppHolidaysIndexRoute = AppHolidaysIndexRouteImport.update({
  id: '/holidays/',
  path: '/holidays/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamsIndexRoute = AppExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamBookingsIndexRoute = AppExamBookingsIndexRouteImport.update({
  id: '/exam-bookings/',
  path: '/exam-bookings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEnglishTestIndexRoute = AppEnglishTestIndexRouteImport.update({
  id: '/english-test/',
  path: '/english-test/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDemoIndexRoute = AppDemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoursePackagesIndexRoute = AppCoursePackagesIndexRouteImport.update({
  id: '/course-packages/',
  path: '/course-packages/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCourseBookingsIndexRoute = AppCourseBookingsIndexRouteImport.update({
  id: '/course-bookings/',
  path: '/course-bookings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConsultationsIndexRoute = AppConsultationsIndexRouteImport.update({
  id: '/consultations/',
  path: '/consultations/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/_dashboard/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppDashboardIndexRoute
  '/route copy': typeof AuthRoutecopyRoute
  '/zoho-failed/': typeof ZohoFailedIndexRoute
  '/zoho-success/': typeof ZohoSuccessIndexRoute
  '/consultations/': typeof AppConsultationsIndexRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/course-bookings/': typeof AppCourseBookingsIndexRoute
  '/course-packages/': typeof AppCoursePackagesIndexRoute
  '/courses/': typeof AppCoursesIndexRoute
  '/demo/': typeof AppDemoIndexRoute
  '/english-test/': typeof AppEnglishTestIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/exam-bookings/': typeof AppExamBookingsIndexRoute
  '/exams/': typeof AppExamsIndexRoute
  '/holidays/': typeof AppHolidaysIndexRoute
  '/mock-test-bookings/': typeof AppMockTestBookingsIndexRoute
  '/mock-tests/': typeof AppMockTestsIndexRoute
  '/payments/': typeof AppPaymentsIndexRoute
  '/routines/': typeof AppRoutinesIndexRoute
  '/sub-courses/': typeof AppSubCoursesIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/videos/': typeof AppVideosIndexRoute
  '/workshop/': typeof AppWorkshopIndexRoute
  '/zoho/': typeof AppZohoIndexRoute
  '/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/login/': typeof AuthLoginIndexRoute
  '/reset-password/': typeof AuthResetPasswordIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppDashboardIndexRoute
  '/route copy': typeof AuthRoutecopyRoute
  '/zoho-failed': typeof ZohoFailedIndexRoute
  '/zoho-success': typeof ZohoSuccessIndexRoute
  '/consultations': typeof AppConsultationsIndexRoute
  '/contacts': typeof AppContactsIndexRoute
  '/course-bookings': typeof AppCourseBookingsIndexRoute
  '/course-packages': typeof AppCoursePackagesIndexRoute
  '/courses': typeof AppCoursesIndexRoute
  '/demo': typeof AppDemoIndexRoute
  '/english-test': typeof AppEnglishTestIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/exam-bookings': typeof AppExamBookingsIndexRoute
  '/exams': typeof AppExamsIndexRoute
  '/holidays': typeof AppHolidaysIndexRoute
  '/mock-test-bookings': typeof AppMockTestBookingsIndexRoute
  '/mock-tests': typeof AppMockTestsIndexRoute
  '/payments': typeof AppPaymentsIndexRoute
  '/routines': typeof AppRoutinesIndexRoute
  '/sub-courses': typeof AppSubCoursesIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/videos': typeof AppVideosIndexRoute
  '/workshop': typeof AppWorkshopIndexRoute
  '/zoho': typeof AppZohoIndexRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/route copy': typeof AuthRoutecopyRoute
  '/zoho-failed/': typeof ZohoFailedIndexRoute
  '/zoho-success/': typeof ZohoSuccessIndexRoute
  '/_app/_dashboard/': typeof AppDashboardIndexRoute
  '/_app/consultations/': typeof AppConsultationsIndexRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/course-bookings/': typeof AppCourseBookingsIndexRoute
  '/_app/course-packages/': typeof AppCoursePackagesIndexRoute
  '/_app/courses/': typeof AppCoursesIndexRoute
  '/_app/demo/': typeof AppDemoIndexRoute
  '/_app/english-test/': typeof AppEnglishTestIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/exam-bookings/': typeof AppExamBookingsIndexRoute
  '/_app/exams/': typeof AppExamsIndexRoute
  '/_app/holidays/': typeof AppHolidaysIndexRoute
  '/_app/mock-test-bookings/': typeof AppMockTestBookingsIndexRoute
  '/_app/mock-tests/': typeof AppMockTestsIndexRoute
  '/_app/payments/': typeof AppPaymentsIndexRoute
  '/_app/routines/': typeof AppRoutinesIndexRoute
  '/_app/sub-courses/': typeof AppSubCoursesIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_app/videos/': typeof AppVideosIndexRoute
  '/_app/workshop/': typeof AppWorkshopIndexRoute
  '/_app/zoho/': typeof AppZohoIndexRoute
  '/_auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/route copy'
    | '/zoho-failed/'
    | '/zoho-success/'
    | '/consultations/'
    | '/contacts/'
    | '/course-bookings/'
    | '/course-packages/'
    | '/courses/'
    | '/demo/'
    | '/english-test/'
    | '/events/'
    | '/exam-bookings/'
    | '/exams/'
    | '/holidays/'
    | '/mock-test-bookings/'
    | '/mock-tests/'
    | '/payments/'
    | '/routines/'
    | '/sub-courses/'
    | '/users/'
    | '/videos/'
    | '/workshop/'
    | '/zoho/'
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/route copy'
    | '/zoho-failed'
    | '/zoho-success'
    | '/consultations'
    | '/contacts'
    | '/course-bookings'
    | '/course-packages'
    | '/courses'
    | '/demo'
    | '/english-test'
    | '/events'
    | '/exam-bookings'
    | '/exams'
    | '/holidays'
    | '/mock-test-bookings'
    | '/mock-tests'
    | '/payments'
    | '/routines'
    | '/sub-courses'
    | '/users'
    | '/videos'
    | '/workshop'
    | '/zoho'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_auth/route copy'
    | '/zoho-failed/'
    | '/zoho-success/'
    | '/_app/_dashboard/'
    | '/_app/consultations/'
    | '/_app/contacts/'
    | '/_app/course-bookings/'
    | '/_app/course-packages/'
    | '/_app/courses/'
    | '/_app/demo/'
    | '/_app/english-test/'
    | '/_app/events/'
    | '/_app/exam-bookings/'
    | '/_app/exams/'
    | '/_app/holidays/'
    | '/_app/mock-test-bookings/'
    | '/_app/mock-tests/'
    | '/_app/payments/'
    | '/_app/routines/'
    | '/_app/sub-courses/'
    | '/_app/users/'
    | '/_app/videos/'
    | '/_app/workshop/'
    | '/_app/zoho/'
    | '/_auth/forgot-password/'
    | '/_auth/login/'
    | '/_auth/reset-password/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ZohoFailedIndexRoute: typeof ZohoFailedIndexRoute
  ZohoSuccessIndexRoute: typeof ZohoSuccessIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zoho-success/': {
      id: '/zoho-success/'
      path: '/zoho-success'
      fullPath: '/zoho-success/'
      preLoaderRoute: typeof ZohoSuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zoho-failed/': {
      id: '/zoho-failed/'
      path: '/zoho-failed'
      fullPath: '/zoho-failed/'
      preLoaderRoute: typeof ZohoFailedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/route copy': {
      id: '/_auth/route copy'
      path: '/route copy'
      fullPath: '/route copy'
      preLoaderRoute: typeof AuthRoutecopyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password/': {
      id: '/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/zoho/': {
      id: '/_app/zoho/'
      path: '/zoho'
      fullPath: '/zoho/'
      preLoaderRoute: typeof AppZohoIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/workshop/': {
      id: '/_app/workshop/'
      path: '/workshop'
      fullPath: '/workshop/'
      preLoaderRoute: typeof AppWorkshopIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/videos/': {
      id: '/_app/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof AppVideosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sub-courses/': {
      id: '/_app/sub-courses/'
      path: '/sub-courses'
      fullPath: '/sub-courses/'
      preLoaderRoute: typeof AppSubCoursesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/routines/': {
      id: '/_app/routines/'
      path: '/routines'
      fullPath: '/routines/'
      preLoaderRoute: typeof AppRoutinesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/payments/': {
      id: '/_app/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AppPaymentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/mock-tests/': {
      id: '/_app/mock-tests/'
      path: '/mock-tests'
      fullPath: '/mock-tests/'
      preLoaderRoute: typeof AppMockTestsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/mock-test-bookings/': {
      id: '/_app/mock-test-bookings/'
      path: '/mock-test-bookings'
      fullPath: '/mock-test-bookings/'
      preLoaderRoute: typeof AppMockTestBookingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/holidays/': {
      id: '/_app/holidays/'
      path: '/holidays'
      fullPath: '/holidays/'
      preLoaderRoute: typeof AppHolidaysIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/exams/': {
      id: '/_app/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof AppExamsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/exam-bookings/': {
      id: '/_app/exam-bookings/'
      path: '/exam-bookings'
      fullPath: '/exam-bookings/'
      preLoaderRoute: typeof AppExamBookingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/english-test/': {
      id: '/_app/english-test/'
      path: '/english-test'
      fullPath: '/english-test/'
      preLoaderRoute: typeof AppEnglishTestIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/demo/': {
      id: '/_app/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof AppDemoIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/courses/': {
      id: '/_app/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/course-packages/': {
      id: '/_app/course-packages/'
      path: '/course-packages'
      fullPath: '/course-packages/'
      preLoaderRoute: typeof AppCoursePackagesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/course-bookings/': {
      id: '/_app/course-bookings/'
      path: '/course-bookings'
      fullPath: '/course-bookings/'
      preLoaderRoute: typeof AppCourseBookingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/consultations/': {
      id: '/_app/consultations/'
      path: '/consultations'
      fullPath: '/consultations/'
      preLoaderRoute: typeof AppConsultationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_dashboard/': {
      id: '/_app/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppConsultationsIndexRoute: typeof AppConsultationsIndexRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppCourseBookingsIndexRoute: typeof AppCourseBookingsIndexRoute
  AppCoursePackagesIndexRoute: typeof AppCoursePackagesIndexRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
  AppDemoIndexRoute: typeof AppDemoIndexRoute
  AppEnglishTestIndexRoute: typeof AppEnglishTestIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppExamBookingsIndexRoute: typeof AppExamBookingsIndexRoute
  AppExamsIndexRoute: typeof AppExamsIndexRoute
  AppHolidaysIndexRoute: typeof AppHolidaysIndexRoute
  AppMockTestBookingsIndexRoute: typeof AppMockTestBookingsIndexRoute
  AppMockTestsIndexRoute: typeof AppMockTestsIndexRoute
  AppPaymentsIndexRoute: typeof AppPaymentsIndexRoute
  AppRoutinesIndexRoute: typeof AppRoutinesIndexRoute
  AppSubCoursesIndexRoute: typeof AppSubCoursesIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppVideosIndexRoute: typeof AppVideosIndexRoute
  AppWorkshopIndexRoute: typeof AppWorkshopIndexRoute
  AppZohoIndexRoute: typeof AppZohoIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppConsultationsIndexRoute: AppConsultationsIndexRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppCourseBookingsIndexRoute: AppCourseBookingsIndexRoute,
  AppCoursePackagesIndexRoute: AppCoursePackagesIndexRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
  AppDemoIndexRoute: AppDemoIndexRoute,
  AppEnglishTestIndexRoute: AppEnglishTestIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppExamBookingsIndexRoute: AppExamBookingsIndexRoute,
  AppExamsIndexRoute: AppExamsIndexRoute,
  AppHolidaysIndexRoute: AppHolidaysIndexRoute,
  AppMockTestBookingsIndexRoute: AppMockTestBookingsIndexRoute,
  AppMockTestsIndexRoute: AppMockTestsIndexRoute,
  AppPaymentsIndexRoute: AppPaymentsIndexRoute,
  AppRoutinesIndexRoute: AppRoutinesIndexRoute,
  AppSubCoursesIndexRoute: AppSubCoursesIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppVideosIndexRoute: AppVideosIndexRoute,
  AppWorkshopIndexRoute: AppWorkshopIndexRoute,
  AppZohoIndexRoute: AppZohoIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthRoutecopyRoute: typeof AuthRoutecopyRoute
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthRoutecopyRoute: AuthRoutecopyRoute,
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ZohoFailedIndexRoute: ZohoFailedIndexRoute,
  ZohoSuccessIndexRoute: ZohoSuccessIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
